/**
 * Embed asset pipeline: reads assets/backgrounds/*.{png,jpg,jpeg,webp,gif}
 * and generates src/client/assets.generated.ts with base64 data so preset
 * backgrounds ship inline in the client bundle (no runtime file serving).
 * Run automatically before tsdown via the package build script.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { dirname, join, basename, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const dir = join(root, 'assets', 'backgrounds')
const out = join(root, 'src', 'client', 'assets.generated.ts')

const MIME = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
}

const entries = []
if (existsSync(dir)) {
  for (const file of readdirSync(dir).sort()) {
    const ext = extname(file).toLowerCase()
    if (MIME[ext] === undefined) continue
    const data = readFileSync(join(dir, file)).toString('base64')
    const key = basename(file, ext).replace(/[^a-zA-Z0-9_-]/g, '_')
    entries.push(`  '${key}': { name: '${basename(file, ext)}', mime: '${MIME[ext]}', data: '${data}' },`)
  }
}

const content = [
  '// AUTO-GENERATED by scripts/embed-assets.mjs — do not edit by hand.',
  'export interface PresetBackground { name: string; mime: string; data: string }',
  'export const PRESET_BACKGROUNDS: Record<string, PresetBackground> = {',
  ...entries,
  '}',
  '',
].join('\n')
writeFileSync(out, content)
console.log(`embed-assets: ${entries.length} asset(s) -> src/client/assets.generated.ts`)
